# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
     
      - name: Publish Https Nuget Package
        id: publish_nuget_https
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: CardboardBox.Extensions/CardboardBox.Extensions.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
      - name: Publish Main Nuget Package
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: CardboardBox.Discord/CardboardBox.Discord.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
          
      - name: Publish Https Nuget Package
        id: publish_nuget_https
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: CardboardBox.Http/CardboardBox.Http.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
     
      - name: Publish Https Nuget Package
        id: publish_nuget_https
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: CardboardBox.Http.Html/CardboardBox.Http.Html.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Publish Https Nuget Package
        id: publish_nuget_https
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: CardboardBox.Http.Files/CardboardBox.Http.Files.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
          
      - name: Publish Reids Nuget Package
        id: publish_nuget_redis
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: CardboardBox.Redis/CardboardBox.Redis.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Publish Json Nuget Package
        id: publish_nuget_json
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: CardboardBox.Json/CardboardBox.Json.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Publish Database Nuget Package
        id: publish_nuget_database
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: CardboardBox.Database/CardboardBox.Database.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}